
stages:
  # - test
  - publish

variables:
  DOCKER_DRIVER: overlay
services:
  - docker:dind

# test:
#   stage: test
#   image: docker
#   before_script:
#     - docker info
#     - apk update && apk add ca-certificates && update-ca-certificates && apk add openssl && apk add curl
#     - wget --no-check-certificate -O ./terraform.zip https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_linux_amd64.zip?_ga=2.64839145.739266491.1506689304-1411664957.1503690670
#     - unzip -d ./test ./terraform.zip
#   script:
#     - cd ./test
#     - ./terraform init
#     - ./terraform apply
#     - ./terraform destroy -force

publish:
  stage: publish
  image: docker
  before_script:
    - docker info
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/bcb-devops/gitlab_backup
    - docker build -t gitlab_backup .
    - docker tag gitlab_backup registry.gitlab.com/bcb-devops/gitlab_backup
    - docker push registry.gitlab.com/bcb-devops/gitlab_backup
    - docker tag gitlab_backup registry.gitlab.com/bcb-devops/gitlab_backup:latest
    - docker push registry.gitlab.com/bcb-devops/gitlab_backup:latest
    - docker tag gitlab_backup registry.gitlab.com/bcb-devops/gitlab_backup:${CI_COMMIT_SHA}
    - docker push registry.gitlab.com/bcb-devops/gitlab_backup:${CI_COMMIT_SHA}
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker tag gitlab_backup flacito/gitlab_backup:latest
    - docker push flacito/gitlab_backup:latest
    - docker tag gitlab_backup flacito/gitlab_backup:${CI_COMMIT_SHA}
    - docker push flacito/gitlab_backup:${CI_COMMIT_SHA}
